steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/gcdemopractise/cloud-run-demo:$SHORT_SHA', 
           '.']
   # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/gcdemopractise/cloud-run-demo:$SHORT_SHA']
